### PR TITLE
Change dependencies requirements for Symfony 3 compatibility

### PR DESCRIPTION
**Pull request by hugues-m**
Runs okay after those modifications.
Should be tagged with major version change though.

### CODE REVIEW

**Comment by eliecharra** [comment]
@hmlb Maybe we should use the new Symfony Lock component instead ?

**Comment by hmlb** [comment]
Thx @eliecharra, I'll check Symfony Lock features and performances and switch if it's okay.

**Comment by eliecharra** [comment]
@hmlb Maybe we could merge this one, and flag this bundle as deprecated in packagist afterwards.

Test need to be fixed to be merged.

**Comment by eliecharra** [comment]
As we change min PHP version, this MR BC break.

It will be released under a 2.x tag.

**Comment by eliecharra** [comment]
Released under https://github.com/kitpages/KitpagesSemaphoreBundle/releases/tag/v2.0.0

**Pull request merged**
